name: IKUUU-Auto-Checkin

on:
  workflow_dispatch:
  schedule:
    - cron: "33 23 * * *"

jobs:
  checkin:
    name: Checkin
    runs-on: ubuntu-latest

    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}
      HOST: ${{ secrets.HOST }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Run Checkin
        id: checkin
        run: node main.js
